1. What is an exception?

represent errrors that occur durring application execution causing termination.
its a booboo and causes your program to crash. 

2. What happens in a try block if the program executes without errors?

it executes one statement after the other in the block and the code runs to completion

3. How does the catch mechanism work for unhandled exceptions?

it throws the exception to the enclosing block unwinding the stack back up and if none of the higher blocks can handle it then te program crashes

4. What happens in a program if an exception block fails to handle an particular error?

Use a general exception
the calling method exits and execution returns to its caller

5. What is the parent class for all exceptions? How does this work?

Exception is the grandaddy

6. How do you determine the type of an error?

Exception.message property

7. What is the purpose of integer checking?

To notify the user that there will be an overflow


8. What is the range of values than a signed Int32 type can contain? State the lowest value and the highest value.

int.32 maxvalue
int.32 minvalue
â€“2147483648 to 2147483647 

9. What is the range of values than an unsigned Int32 type can contain? State the lowest value and the highest value. What is the difference between a signed integer and an unsigned integer? Can signed integers and unsigned integers represent the same amount of numbers?

0 to 4,294,967,295; The difference is that in a signed int, one of the bits is used to indicate if the number is positive or negative. In and unsigned int, that bit is used to hold a value. The effect is that you can hold twice the absolute values in an unsigned in as you can in a signed int. Or more plainly, the range of the C# integer is -2,147,483,648 to 2,147,483,647 while the range of the uint is 0 to 4,294,967,295.

you get the same number of integers

10. What does the finally block do?

The way to ensure that a statement is always run, whether or not an exception
has been thrown, is to write that statement inside a finally block. A finally block occurs immediately after a try block or immediately after the last catch handler after a try block.

it always runs. it never gives up

11. (Thought question) When would you not use a finally block in a try/catch construction?

when you have scarce resources